### PR TITLE
Fix  anchors position

### PR DESCRIPTION
**Pull request by KumaNNN**
Fix  anchors position 

See #118

### CODE REVIEW

**Comment by KumaNNN** [comment]
@SukkaW

**Comment by SukkaW** [comment]
The unit tests are broken. Would you mind fixing them?

**Comment by KumaNNN** [comment]
> The unit tests are broken. Would you mind fixing them?

Are you talking about the contents under the `test` directory? I'll try, but I'm not a professional programmer and can't guarantee success.

**Comment by KumaNNN** [comment]
Unit test OK
@SukkaW

**Comment by curbengh** [comment]
The `.header-anchor` class is styled by your theme, so `float: none` should be added there.

When there is no style, it's displayed as following:
test

**Pull request closed without merging**
